services:
  pg:
    container_name: links
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"

  web:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DEBUG=True
    depends_on:
      - pg
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000